-- IF OBJECT_ID(N'[dbo].[TREE]', N'U') IS NOT NULL
--     DROP TABLE [dbo].[TREE]
-- GO
CREATE TABLE [dbo].[TREE]
(
[Id] INT IDENTITY (1, 1) NOT NULL,
[PLT_CN] BIGINT NULL,
[INVYR] INT NULL,
[CONDID] INT NULL,
[STATECD] INT NOT NULL,
[COUNTYCD] INT NOT NULL,
[CYCLE] INT NULL,
[PLOT] INT NULL,
[TPA_UNADJ] FLOAT NULL,
[DRYBIO_BOLE] FLOAT NULL,
[DRYBIO_STUMP] FLOAT NULL,
[DRYBIO_TOP] FLOAT NULL,
[DRYBIO_SAPLING] FLOAT NULL,
[DRYBIO_WDLD_SPP] FLOAT NULL,
[DRYBIO_AG] FLOAT NULL,
[DRYBIO_BG] FLOAT NULL
  CONSTRAINT PK_tree_Id PRIMARY KEY CLUSTERED (Id)
);
GO

-- IF OBJECT_ID(N'[dbo].[COND]', N'U') IS NOT NULL
--     DROP TABLE [dbo].[COND]
-- GO
CREATE TABLE [dbo].[COND]
(
 [Id] INT IDENTITY (1, 1) NOT NULL,
 [PLT_CN] BIGINT NULL,
 [INVYR] INT NULL,
 [CONDID] INT NULL,
 [STATECD] INT NOT NULL,
 [COUNTYCD] INT NOT NULL,
 [CYCLE] INT NULL,
 [PLOT] INT NULL
   CONSTRAINT PK_cond_Id PRIMARY KEY CLUSTERED (Id)
);
GO

-- IF OBJECT_ID(N'[dbo].[PLOTSNAP]', N'U') IS NOT NULL
--     DROP TABLE [dbo].[PLOTSNAP]
-- GO
CREATE TABLE [dbo].[PLOTSNAP]
(
 [Id] INT IDENTITY (1, 1) NOT NULL,
 [CN] BIGINT NULL,
 [INVYR] INT NULL,
 [STATECD] INT NOT NULL,
 [COUNTYCD] INT NOT NULL,
 [CYCLE] INT NULL,
 [PLOT] INT NULL
   CONSTRAINT PK_plotsnap_Id PRIMARY KEY CLUSTERED (Id)
);
